// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.2
// source: proto/stellguard/agent/v1/agent.proto

package agentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StellGuardAgent_FetchWorkloadCertificate_FullMethodName = "/stellguard.agent.v1.StellGuardAgent/FetchWorkloadCertificate"
	StellGuardAgent_WatchCredentialBundle_FullMethodName    = "/stellguard.agent.v1.StellGuardAgent/WatchCredentialBundle"
	StellGuardAgent_FetchTrustBundle_FullMethodName         = "/stellguard.agent.v1.StellGuardAgent/FetchTrustBundle"
)

// StellGuardAgentClient is the client API for StellGuardAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StellGuardAgentClient interface {
	FetchWorkloadCertificate(ctx context.Context, in *FetchWorkloadCertificateRequest, opts ...grpc.CallOption) (*CredentialBundle, error)
	WatchCredentialBundle(ctx context.Context, in *WatchCredentialBundleRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CredentialBundle], error)
	FetchTrustBundle(ctx context.Context, in *FetchTrustBundleRequest, opts ...grpc.CallOption) (*TrustBundle, error)
}

type stellGuardAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewStellGuardAgentClient(cc grpc.ClientConnInterface) StellGuardAgentClient {
	return &stellGuardAgentClient{cc}
}

func (c *stellGuardAgentClient) FetchWorkloadCertificate(ctx context.Context, in *FetchWorkloadCertificateRequest, opts ...grpc.CallOption) (*CredentialBundle, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CredentialBundle)
	err := c.cc.Invoke(ctx, StellGuardAgent_FetchWorkloadCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stellGuardAgentClient) WatchCredentialBundle(ctx context.Context, in *WatchCredentialBundleRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CredentialBundle], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StellGuardAgent_ServiceDesc.Streams[0], StellGuardAgent_WatchCredentialBundle_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchCredentialBundleRequest, CredentialBundle]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StellGuardAgent_WatchCredentialBundleClient = grpc.ServerStreamingClient[CredentialBundle]

func (c *stellGuardAgentClient) FetchTrustBundle(ctx context.Context, in *FetchTrustBundleRequest, opts ...grpc.CallOption) (*TrustBundle, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrustBundle)
	err := c.cc.Invoke(ctx, StellGuardAgent_FetchTrustBundle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StellGuardAgentServer is the server API for StellGuardAgent service.
// All implementations must embed UnimplementedStellGuardAgentServer
// for forward compatibility.
type StellGuardAgentServer interface {
	FetchWorkloadCertificate(context.Context, *FetchWorkloadCertificateRequest) (*CredentialBundle, error)
	WatchCredentialBundle(*WatchCredentialBundleRequest, grpc.ServerStreamingServer[CredentialBundle]) error
	FetchTrustBundle(context.Context, *FetchTrustBundleRequest) (*TrustBundle, error)
	mustEmbedUnimplementedStellGuardAgentServer()
}

// UnimplementedStellGuardAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStellGuardAgentServer struct{}

func (UnimplementedStellGuardAgentServer) FetchWorkloadCertificate(context.Context, *FetchWorkloadCertificateRequest) (*CredentialBundle, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchWorkloadCertificate not implemented")
}
func (UnimplementedStellGuardAgentServer) WatchCredentialBundle(*WatchCredentialBundleRequest, grpc.ServerStreamingServer[CredentialBundle]) error {
	return status.Error(codes.Unimplemented, "method WatchCredentialBundle not implemented")
}
func (UnimplementedStellGuardAgentServer) FetchTrustBundle(context.Context, *FetchTrustBundleRequest) (*TrustBundle, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchTrustBundle not implemented")
}
func (UnimplementedStellGuardAgentServer) mustEmbedUnimplementedStellGuardAgentServer() {}
func (UnimplementedStellGuardAgentServer) testEmbeddedByValue()                         {}

// UnsafeStellGuardAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StellGuardAgentServer will
// result in compilation errors.
type UnsafeStellGuardAgentServer interface {
	mustEmbedUnimplementedStellGuardAgentServer()
}

func RegisterStellGuardAgentServer(s grpc.ServiceRegistrar, srv StellGuardAgentServer) {
	// If the following call panics, it indicates UnimplementedStellGuardAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StellGuardAgent_ServiceDesc, srv)
}

func _StellGuardAgent_FetchWorkloadCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchWorkloadCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StellGuardAgentServer).FetchWorkloadCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StellGuardAgent_FetchWorkloadCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StellGuardAgentServer).FetchWorkloadCertificate(ctx, req.(*FetchWorkloadCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StellGuardAgent_WatchCredentialBundle_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchCredentialBundleRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StellGuardAgentServer).WatchCredentialBundle(m, &grpc.GenericServerStream[WatchCredentialBundleRequest, CredentialBundle]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StellGuardAgent_WatchCredentialBundleServer = grpc.ServerStreamingServer[CredentialBundle]

func _StellGuardAgent_FetchTrustBundle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchTrustBundleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StellGuardAgentServer).FetchTrustBundle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StellGuardAgent_FetchTrustBundle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StellGuardAgentServer).FetchTrustBundle(ctx, req.(*FetchTrustBundleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StellGuardAgent_ServiceDesc is the grpc.ServiceDesc for StellGuardAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StellGuardAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stellguard.agent.v1.StellGuardAgent",
	HandlerType: (*StellGuardAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchWorkloadCertificate",
			Handler:    _StellGuardAgent_FetchWorkloadCertificate_Handler,
		},
		{
			MethodName: "FetchTrustBundle",
			Handler:    _StellGuardAgent_FetchTrustBundle_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchCredentialBundle",
			Handler:       _StellGuardAgent_WatchCredentialBundle_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/stellguard/agent/v1/agent.proto",
}
