// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.2
// source: proto/stellguard/agent/v1/agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchWorkloadCertificateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpiffeId      string                 `protobuf:"bytes,1,opt,name=spiffe_id,json=spiffeId,proto3" json:"spiffe_id,omitempty"`
	DnsNames      []string               `protobuf:"bytes,2,rep,name=dns_names,json=dnsNames,proto3" json:"dns_names,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	ForceRotate   bool                   `protobuf:"varint,4,opt,name=force_rotate,json=forceRotate,proto3" json:"force_rotate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchWorkloadCertificateRequest) Reset() {
	*x = FetchWorkloadCertificateRequest{}
	mi := &file_proto_stellguard_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchWorkloadCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchWorkloadCertificateRequest) ProtoMessage() {}

func (x *FetchWorkloadCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stellguard_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchWorkloadCertificateRequest.ProtoReflect.Descriptor instead.
func (*FetchWorkloadCertificateRequest) Descriptor() ([]byte, []int) {
	return file_proto_stellguard_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *FetchWorkloadCertificateRequest) GetSpiffeId() string {
	if x != nil {
		return x.SpiffeId
	}
	return ""
}

func (x *FetchWorkloadCertificateRequest) GetDnsNames() []string {
	if x != nil {
		return x.DnsNames
	}
	return nil
}

func (x *FetchWorkloadCertificateRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *FetchWorkloadCertificateRequest) GetForceRotate() bool {
	if x != nil {
		return x.ForceRotate
	}
	return false
}

type WatchCredentialBundleRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SpiffeId           string                 `protobuf:"bytes,1,opt,name=spiffe_id,json=spiffeId,proto3" json:"spiffe_id,omitempty"`
	DnsNames           []string               `protobuf:"bytes,2,rep,name=dns_names,json=dnsNames,proto3" json:"dns_names,omitempty"`
	TtlSeconds         int64                  `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	RenewalHintSeconds int64                  `protobuf:"varint,4,opt,name=renewal_hint_seconds,json=renewalHintSeconds,proto3" json:"renewal_hint_seconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WatchCredentialBundleRequest) Reset() {
	*x = WatchCredentialBundleRequest{}
	mi := &file_proto_stellguard_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchCredentialBundleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchCredentialBundleRequest) ProtoMessage() {}

func (x *WatchCredentialBundleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stellguard_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchCredentialBundleRequest.ProtoReflect.Descriptor instead.
func (*WatchCredentialBundleRequest) Descriptor() ([]byte, []int) {
	return file_proto_stellguard_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *WatchCredentialBundleRequest) GetSpiffeId() string {
	if x != nil {
		return x.SpiffeId
	}
	return ""
}

func (x *WatchCredentialBundleRequest) GetDnsNames() []string {
	if x != nil {
		return x.DnsNames
	}
	return nil
}

func (x *WatchCredentialBundleRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *WatchCredentialBundleRequest) GetRenewalHintSeconds() int64 {
	if x != nil {
		return x.RenewalHintSeconds
	}
	return 0
}

type CredentialBundle struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CertificatePem       string                 `protobuf:"bytes,1,opt,name=certificate_pem,json=certificatePem,proto3" json:"certificate_pem,omitempty"`
	PrivateKeyPem        string                 `protobuf:"bytes,2,opt,name=private_key_pem,json=privateKeyPem,proto3" json:"private_key_pem,omitempty"`
	TrustBundlePem       string                 `protobuf:"bytes,3,opt,name=trust_bundle_pem,json=trustBundlePem,proto3" json:"trust_bundle_pem,omitempty"`
	Issuer               string                 `protobuf:"bytes,4,opt,name=issuer,proto3" json:"issuer,omitempty"`
	KeyId                string                 `protobuf:"bytes,5,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	SerialNumber         string                 `protobuf:"bytes,6,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	ExpiresAtUnixSeconds int64                  `protobuf:"varint,7,opt,name=expires_at_unix_seconds,json=expiresAtUnixSeconds,proto3" json:"expires_at_unix_seconds,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CredentialBundle) Reset() {
	*x = CredentialBundle{}
	mi := &file_proto_stellguard_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialBundle) ProtoMessage() {}

func (x *CredentialBundle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stellguard_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialBundle.ProtoReflect.Descriptor instead.
func (*CredentialBundle) Descriptor() ([]byte, []int) {
	return file_proto_stellguard_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *CredentialBundle) GetCertificatePem() string {
	if x != nil {
		return x.CertificatePem
	}
	return ""
}

func (x *CredentialBundle) GetPrivateKeyPem() string {
	if x != nil {
		return x.PrivateKeyPem
	}
	return ""
}

func (x *CredentialBundle) GetTrustBundlePem() string {
	if x != nil {
		return x.TrustBundlePem
	}
	return ""
}

func (x *CredentialBundle) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *CredentialBundle) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *CredentialBundle) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *CredentialBundle) GetExpiresAtUnixSeconds() int64 {
	if x != nil {
		return x.ExpiresAtUnixSeconds
	}
	return 0
}

type FetchTrustBundleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrustDomain   string                 `protobuf:"bytes,1,opt,name=trust_domain,json=trustDomain,proto3" json:"trust_domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchTrustBundleRequest) Reset() {
	*x = FetchTrustBundleRequest{}
	mi := &file_proto_stellguard_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchTrustBundleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchTrustBundleRequest) ProtoMessage() {}

func (x *FetchTrustBundleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stellguard_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchTrustBundleRequest.ProtoReflect.Descriptor instead.
func (*FetchTrustBundleRequest) Descriptor() ([]byte, []int) {
	return file_proto_stellguard_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *FetchTrustBundleRequest) GetTrustDomain() string {
	if x != nil {
		return x.TrustDomain
	}
	return ""
}

type TrustBundle struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TrustDomain    string                 `protobuf:"bytes,1,opt,name=trust_domain,json=trustDomain,proto3" json:"trust_domain,omitempty"`
	TrustBundlePem string                 `protobuf:"bytes,2,opt,name=trust_bundle_pem,json=trustBundlePem,proto3" json:"trust_bundle_pem,omitempty"`
	KeyId          string                 `protobuf:"bytes,3,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TrustBundle) Reset() {
	*x = TrustBundle{}
	mi := &file_proto_stellguard_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrustBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrustBundle) ProtoMessage() {}

func (x *TrustBundle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stellguard_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrustBundle.ProtoReflect.Descriptor instead.
func (*TrustBundle) Descriptor() ([]byte, []int) {
	return file_proto_stellguard_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *TrustBundle) GetTrustDomain() string {
	if x != nil {
		return x.TrustDomain
	}
	return ""
}

func (x *TrustBundle) GetTrustBundlePem() string {
	if x != nil {
		return x.TrustBundlePem
	}
	return ""
}

func (x *TrustBundle) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

var File_proto_stellguard_agent_v1_agent_proto protoreflect.FileDescriptor

const file_proto_stellguard_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"%proto/stellguard/agent/v1/agent.proto\x12\x13stellguard.agent.v1\"\x9f\x01\n" +
	"\x1fFetchWorkloadCertificateRequest\x12\x1b\n" +
	"\tspiffe_id\x18\x01 \x01(\tR\bspiffeId\x12\x1b\n" +
	"\tdns_names\x18\x02 \x03(\tR\bdnsNames\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\x12!\n" +
	"\fforce_rotate\x18\x04 \x01(\bR\vforceRotate\"\xab\x01\n" +
	"\x1cWatchCredentialBundleRequest\x12\x1b\n" +
	"\tspiffe_id\x18\x01 \x01(\tR\bspiffeId\x12\x1b\n" +
	"\tdns_names\x18\x02 \x03(\tR\bdnsNames\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\x120\n" +
	"\x14renewal_hint_seconds\x18\x04 \x01(\x03R\x12renewalHintSeconds\"\x98\x02\n" +
	"\x10CredentialBundle\x12'\n" +
	"\x0fcertificate_pem\x18\x01 \x01(\tR\x0ecertificatePem\x12&\n" +
	"\x0fprivate_key_pem\x18\x02 \x01(\tR\rprivateKeyPem\x12(\n" +
	"\x10trust_bundle_pem\x18\x03 \x01(\tR\x0etrustBundlePem\x12\x16\n" +
	"\x06issuer\x18\x04 \x01(\tR\x06issuer\x12\x15\n" +
	"\x06key_id\x18\x05 \x01(\tR\x05keyId\x12#\n" +
	"\rserial_number\x18\x06 \x01(\tR\fserialNumber\x125\n" +
	"\x17expires_at_unix_seconds\x18\a \x01(\x03R\x14expiresAtUnixSeconds\"<\n" +
	"\x17FetchTrustBundleRequest\x12!\n" +
	"\ftrust_domain\x18\x01 \x01(\tR\vtrustDomain\"q\n" +
	"\vTrustBundle\x12!\n" +
	"\ftrust_domain\x18\x01 \x01(\tR\vtrustDomain\x12(\n" +
	"\x10trust_bundle_pem\x18\x02 \x01(\tR\x0etrustBundlePem\x12\x15\n" +
	"\x06key_id\x18\x03 \x01(\tR\x05keyId2\xe3\x02\n" +
	"\x0fStellGuardAgent\x12w\n" +
	"\x18FetchWorkloadCertificate\x124.stellguard.agent.v1.FetchWorkloadCertificateRequest\x1a%.stellguard.agent.v1.CredentialBundle\x12s\n" +
	"\x15WatchCredentialBundle\x121.stellguard.agent.v1.WatchCredentialBundleRequest\x1a%.stellguard.agent.v1.CredentialBundle0\x01\x12b\n" +
	"\x10FetchTrustBundle\x12,.stellguard.agent.v1.FetchTrustBundleRequest\x1a .stellguard.agent.v1.TrustBundleBIZGgithub.com/stellhub/stellguard-go-sdk/proto/stellguard/agent/v1;agentv1b\x06proto3"

var (
	file_proto_stellguard_agent_v1_agent_proto_rawDescOnce sync.Once
	file_proto_stellguard_agent_v1_agent_proto_rawDescData []byte
)

func file_proto_stellguard_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_proto_stellguard_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_proto_stellguard_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_stellguard_agent_v1_agent_proto_rawDesc), len(file_proto_stellguard_agent_v1_agent_proto_rawDesc)))
	})
	return file_proto_stellguard_agent_v1_agent_proto_rawDescData
}

var file_proto_stellguard_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_stellguard_agent_v1_agent_proto_goTypes = []any{
	(*FetchWorkloadCertificateRequest)(nil), // 0: stellguard.agent.v1.FetchWorkloadCertificateRequest
	(*WatchCredentialBundleRequest)(nil),    // 1: stellguard.agent.v1.WatchCredentialBundleRequest
	(*CredentialBundle)(nil),                // 2: stellguard.agent.v1.CredentialBundle
	(*FetchTrustBundleRequest)(nil),         // 3: stellguard.agent.v1.FetchTrustBundleRequest
	(*TrustBundle)(nil),                     // 4: stellguard.agent.v1.TrustBundle
}
var file_proto_stellguard_agent_v1_agent_proto_depIdxs = []int32{
	0, // 0: stellguard.agent.v1.StellGuardAgent.FetchWorkloadCertificate:input_type -> stellguard.agent.v1.FetchWorkloadCertificateRequest
	1, // 1: stellguard.agent.v1.StellGuardAgent.WatchCredentialBundle:input_type -> stellguard.agent.v1.WatchCredentialBundleRequest
	3, // 2: stellguard.agent.v1.StellGuardAgent.FetchTrustBundle:input_type -> stellguard.agent.v1.FetchTrustBundleRequest
	2, // 3: stellguard.agent.v1.StellGuardAgent.FetchWorkloadCertificate:output_type -> stellguard.agent.v1.CredentialBundle
	2, // 4: stellguard.agent.v1.StellGuardAgent.WatchCredentialBundle:output_type -> stellguard.agent.v1.CredentialBundle
	4, // 5: stellguard.agent.v1.StellGuardAgent.FetchTrustBundle:output_type -> stellguard.agent.v1.TrustBundle
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_stellguard_agent_v1_agent_proto_init() }
func file_proto_stellguard_agent_v1_agent_proto_init() {
	if File_proto_stellguard_agent_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_stellguard_agent_v1_agent_proto_rawDesc), len(file_proto_stellguard_agent_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_stellguard_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_proto_stellguard_agent_v1_agent_proto_depIdxs,
		MessageInfos:      file_proto_stellguard_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_proto_stellguard_agent_v1_agent_proto = out.File
	file_proto_stellguard_agent_v1_agent_proto_goTypes = nil
	file_proto_stellguard_agent_v1_agent_proto_depIdxs = nil
}
