// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.2
// source: proto/stellguard/agent/v1/workload.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchWorkloadCredentialRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Audience          string                 `protobuf:"bytes,1,opt,name=audience,proto3" json:"audience,omitempty"`
	IncludePrivateKey *bool                  `protobuf:"varint,2,opt,name=include_private_key,json=includePrivateKey,proto3,oneof" json:"include_private_key,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FetchWorkloadCredentialRequest) Reset() {
	*x = FetchWorkloadCredentialRequest{}
	mi := &file_proto_stellguard_agent_v1_workload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchWorkloadCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchWorkloadCredentialRequest) ProtoMessage() {}

func (x *FetchWorkloadCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stellguard_agent_v1_workload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchWorkloadCredentialRequest.ProtoReflect.Descriptor instead.
func (*FetchWorkloadCredentialRequest) Descriptor() ([]byte, []int) {
	return file_proto_stellguard_agent_v1_workload_proto_rawDescGZIP(), []int{0}
}

func (x *FetchWorkloadCredentialRequest) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *FetchWorkloadCredentialRequest) GetIncludePrivateKey() bool {
	if x != nil && x.IncludePrivateKey != nil {
		return *x.IncludePrivateKey
	}
	return false
}

type WatchWorkloadCredentialRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SendCurrent       *bool                  `protobuf:"varint,1,opt,name=send_current,json=sendCurrent,proto3,oneof" json:"send_current,omitempty"`
	Audience          string                 `protobuf:"bytes,2,opt,name=audience,proto3" json:"audience,omitempty"`
	IncludePrivateKey *bool                  `protobuf:"varint,3,opt,name=include_private_key,json=includePrivateKey,proto3,oneof" json:"include_private_key,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WatchWorkloadCredentialRequest) Reset() {
	*x = WatchWorkloadCredentialRequest{}
	mi := &file_proto_stellguard_agent_v1_workload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchWorkloadCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchWorkloadCredentialRequest) ProtoMessage() {}

func (x *WatchWorkloadCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stellguard_agent_v1_workload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchWorkloadCredentialRequest.ProtoReflect.Descriptor instead.
func (*WatchWorkloadCredentialRequest) Descriptor() ([]byte, []int) {
	return file_proto_stellguard_agent_v1_workload_proto_rawDescGZIP(), []int{1}
}

func (x *WatchWorkloadCredentialRequest) GetSendCurrent() bool {
	if x != nil && x.SendCurrent != nil {
		return *x.SendCurrent
	}
	return false
}

func (x *WatchWorkloadCredentialRequest) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *WatchWorkloadCredentialRequest) GetIncludePrivateKey() bool {
	if x != nil && x.IncludePrivateKey != nil {
		return *x.IncludePrivateKey
	}
	return false
}

type GetTrustBundleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrustDomain   string                 `protobuf:"bytes,1,opt,name=trust_domain,json=trustDomain,proto3" json:"trust_domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrustBundleRequest) Reset() {
	*x = GetTrustBundleRequest{}
	mi := &file_proto_stellguard_agent_v1_workload_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrustBundleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrustBundleRequest) ProtoMessage() {}

func (x *GetTrustBundleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stellguard_agent_v1_workload_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrustBundleRequest.ProtoReflect.Descriptor instead.
func (*GetTrustBundleRequest) Descriptor() ([]byte, []int) {
	return file_proto_stellguard_agent_v1_workload_proto_rawDescGZIP(), []int{2}
}

func (x *GetTrustBundleRequest) GetTrustDomain() string {
	if x != nil {
		return x.TrustDomain
	}
	return ""
}

type GetAgentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentStatusRequest) Reset() {
	*x = GetAgentStatusRequest{}
	mi := &file_proto_stellguard_agent_v1_workload_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentStatusRequest) ProtoMessage() {}

func (x *GetAgentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stellguard_agent_v1_workload_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentStatusRequest.ProtoReflect.Descriptor instead.
func (*GetAgentStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_stellguard_agent_v1_workload_proto_rawDescGZIP(), []int{3}
}

type WorkloadCredential struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Slot                string                 `protobuf:"bytes,1,opt,name=slot,proto3" json:"slot,omitempty"`
	CertificatePem      string                 `protobuf:"bytes,2,opt,name=certificate_pem,json=certificatePem,proto3" json:"certificate_pem,omitempty"`
	PrivateKeyPem       string                 `protobuf:"bytes,3,opt,name=private_key_pem,json=privateKeyPem,proto3" json:"private_key_pem,omitempty"`
	CertificateChainPem string                 `protobuf:"bytes,4,opt,name=certificate_chain_pem,json=certificateChainPem,proto3" json:"certificate_chain_pem,omitempty"`
	TrustBundlePem      string                 `protobuf:"bytes,5,opt,name=trust_bundle_pem,json=trustBundlePem,proto3" json:"trust_bundle_pem,omitempty"`
	TrustDomain         string                 `protobuf:"bytes,6,opt,name=trust_domain,json=trustDomain,proto3" json:"trust_domain,omitempty"`
	AgentId             string                 `protobuf:"bytes,7,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	NodeId              string                 `protobuf:"bytes,8,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	IdentityId          string                 `protobuf:"bytes,9,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	SessionId           string                 `protobuf:"bytes,10,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	LeaseId             string                 `protobuf:"bytes,11,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	RenewalGroupId      string                 `protobuf:"bytes,12,opt,name=renewal_group_id,json=renewalGroupId,proto3" json:"renewal_group_id,omitempty"`
	SpiffeId            string                 `protobuf:"bytes,13,opt,name=spiffe_id,json=spiffeId,proto3" json:"spiffe_id,omitempty"`
	DnsNames            []string               `protobuf:"bytes,14,rep,name=dns_names,json=dnsNames,proto3" json:"dns_names,omitempty"`
	SerialNumber        string                 `protobuf:"bytes,15,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	KeyVersionId        string                 `protobuf:"bytes,16,opt,name=key_version_id,json=keyVersionId,proto3" json:"key_version_id,omitempty"`
	KeyVersionLabel     string                 `protobuf:"bytes,17,opt,name=key_version_label,json=keyVersionLabel,proto3" json:"key_version_label,omitempty"`
	BundleId            string                 `protobuf:"bytes,18,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	BundleVersion       int64                  `protobuf:"varint,19,opt,name=bundle_version,json=bundleVersion,proto3" json:"bundle_version,omitempty"`
	CertificateSha256   string                 `protobuf:"bytes,20,opt,name=certificate_sha256,json=certificateSha256,proto3" json:"certificate_sha256,omitempty"`
	NotBefore           string                 `protobuf:"bytes,21,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter            string                 `protobuf:"bytes,22,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	RenewAfter          string                 `protobuf:"bytes,23,opt,name=renew_after,json=renewAfter,proto3" json:"renew_after,omitempty"`
	UpdatedAt           string                 `protobuf:"bytes,24,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *WorkloadCredential) Reset() {
	*x = WorkloadCredential{}
	mi := &file_proto_stellguard_agent_v1_workload_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadCredential) ProtoMessage() {}

func (x *WorkloadCredential) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stellguard_agent_v1_workload_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadCredential.ProtoReflect.Descriptor instead.
func (*WorkloadCredential) Descriptor() ([]byte, []int) {
	return file_proto_stellguard_agent_v1_workload_proto_rawDescGZIP(), []int{4}
}

func (x *WorkloadCredential) GetSlot() string {
	if x != nil {
		return x.Slot
	}
	return ""
}

func (x *WorkloadCredential) GetCertificatePem() string {
	if x != nil {
		return x.CertificatePem
	}
	return ""
}

func (x *WorkloadCredential) GetPrivateKeyPem() string {
	if x != nil {
		return x.PrivateKeyPem
	}
	return ""
}

func (x *WorkloadCredential) GetCertificateChainPem() string {
	if x != nil {
		return x.CertificateChainPem
	}
	return ""
}

func (x *WorkloadCredential) GetTrustBundlePem() string {
	if x != nil {
		return x.TrustBundlePem
	}
	return ""
}

func (x *WorkloadCredential) GetTrustDomain() string {
	if x != nil {
		return x.TrustDomain
	}
	return ""
}

func (x *WorkloadCredential) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *WorkloadCredential) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *WorkloadCredential) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *WorkloadCredential) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *WorkloadCredential) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *WorkloadCredential) GetRenewalGroupId() string {
	if x != nil {
		return x.RenewalGroupId
	}
	return ""
}

func (x *WorkloadCredential) GetSpiffeId() string {
	if x != nil {
		return x.SpiffeId
	}
	return ""
}

func (x *WorkloadCredential) GetDnsNames() []string {
	if x != nil {
		return x.DnsNames
	}
	return nil
}

func (x *WorkloadCredential) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *WorkloadCredential) GetKeyVersionId() string {
	if x != nil {
		return x.KeyVersionId
	}
	return ""
}

func (x *WorkloadCredential) GetKeyVersionLabel() string {
	if x != nil {
		return x.KeyVersionLabel
	}
	return ""
}

func (x *WorkloadCredential) GetBundleId() string {
	if x != nil {
		return x.BundleId
	}
	return ""
}

func (x *WorkloadCredential) GetBundleVersion() int64 {
	if x != nil {
		return x.BundleVersion
	}
	return 0
}

func (x *WorkloadCredential) GetCertificateSha256() string {
	if x != nil {
		return x.CertificateSha256
	}
	return ""
}

func (x *WorkloadCredential) GetNotBefore() string {
	if x != nil {
		return x.NotBefore
	}
	return ""
}

func (x *WorkloadCredential) GetNotAfter() string {
	if x != nil {
		return x.NotAfter
	}
	return ""
}

func (x *WorkloadCredential) GetRenewAfter() string {
	if x != nil {
		return x.RenewAfter
	}
	return ""
}

func (x *WorkloadCredential) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type TrustBundle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrustDomain   string                 `protobuf:"bytes,1,opt,name=trust_domain,json=trustDomain,proto3" json:"trust_domain,omitempty"`
	BundleId      string                 `protobuf:"bytes,2,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	BundleVersion int64                  `protobuf:"varint,3,opt,name=bundle_version,json=bundleVersion,proto3" json:"bundle_version,omitempty"`
	KeyVersionId  string                 `protobuf:"bytes,4,opt,name=key_version_id,json=keyVersionId,proto3" json:"key_version_id,omitempty"`
	BundlePem     string                 `protobuf:"bytes,5,opt,name=bundle_pem,json=bundlePem,proto3" json:"bundle_pem,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrustBundle) Reset() {
	*x = TrustBundle{}
	mi := &file_proto_stellguard_agent_v1_workload_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrustBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrustBundle) ProtoMessage() {}

func (x *TrustBundle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stellguard_agent_v1_workload_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrustBundle.ProtoReflect.Descriptor instead.
func (*TrustBundle) Descriptor() ([]byte, []int) {
	return file_proto_stellguard_agent_v1_workload_proto_rawDescGZIP(), []int{5}
}

func (x *TrustBundle) GetTrustDomain() string {
	if x != nil {
		return x.TrustDomain
	}
	return ""
}

func (x *TrustBundle) GetBundleId() string {
	if x != nil {
		return x.BundleId
	}
	return ""
}

func (x *TrustBundle) GetBundleVersion() int64 {
	if x != nil {
		return x.BundleVersion
	}
	return 0
}

func (x *TrustBundle) GetKeyVersionId() string {
	if x != nil {
		return x.KeyVersionId
	}
	return ""
}

func (x *TrustBundle) GetBundlePem() string {
	if x != nil {
		return x.BundlePem
	}
	return ""
}

func (x *TrustBundle) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type AgentStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	TrustDomain   string                 `protobuf:"bytes,4,opt,name=trust_domain,json=trustDomain,proto3" json:"trust_domain,omitempty"`
	SessionId     string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,6,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	LastRenewalAt string                 `protobuf:"bytes,7,opt,name=last_renewal_at,json=lastRenewalAt,proto3" json:"last_renewal_at,omitempty"`
	LastError     string                 `protobuf:"bytes,8,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	UdsPath       string                 `protobuf:"bytes,9,opt,name=uds_path,json=udsPath,proto3" json:"uds_path,omitempty"`
	StartedAt     string                 `protobuf:"bytes,10,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	BundleVersion int64                  `protobuf:"varint,11,opt,name=bundle_version,json=bundleVersion,proto3" json:"bundle_version,omitempty"`
	KeyVersionId  string                 `protobuf:"bytes,12,opt,name=key_version_id,json=keyVersionId,proto3" json:"key_version_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStatus) Reset() {
	*x = AgentStatus{}
	mi := &file_proto_stellguard_agent_v1_workload_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatus) ProtoMessage() {}

func (x *AgentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stellguard_agent_v1_workload_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStatus.ProtoReflect.Descriptor instead.
func (*AgentStatus) Descriptor() ([]byte, []int) {
	return file_proto_stellguard_agent_v1_workload_proto_rawDescGZIP(), []int{6}
}

func (x *AgentStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *AgentStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AgentStatus) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentStatus) GetTrustDomain() string {
	if x != nil {
		return x.TrustDomain
	}
	return ""
}

func (x *AgentStatus) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AgentStatus) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AgentStatus) GetLastRenewalAt() string {
	if x != nil {
		return x.LastRenewalAt
	}
	return ""
}

func (x *AgentStatus) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *AgentStatus) GetUdsPath() string {
	if x != nil {
		return x.UdsPath
	}
	return ""
}

func (x *AgentStatus) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *AgentStatus) GetBundleVersion() int64 {
	if x != nil {
		return x.BundleVersion
	}
	return 0
}

func (x *AgentStatus) GetKeyVersionId() string {
	if x != nil {
		return x.KeyVersionId
	}
	return ""
}

var File_proto_stellguard_agent_v1_workload_proto protoreflect.FileDescriptor

const file_proto_stellguard_agent_v1_workload_proto_rawDesc = "" +
	"\n" +
	"(proto/stellguard/agent/v1/workload.proto\x12\x13stellguard.agent.v1\"\x89\x01\n" +
	"\x1eFetchWorkloadCredentialRequest\x12\x1a\n" +
	"\baudience\x18\x01 \x01(\tR\baudience\x123\n" +
	"\x13include_private_key\x18\x02 \x01(\bH\x00R\x11includePrivateKey\x88\x01\x01B\x16\n" +
	"\x14_include_private_key\"\xc2\x01\n" +
	"\x1eWatchWorkloadCredentialRequest\x12&\n" +
	"\fsend_current\x18\x01 \x01(\bH\x00R\vsendCurrent\x88\x01\x01\x12\x1a\n" +
	"\baudience\x18\x02 \x01(\tR\baudience\x123\n" +
	"\x13include_private_key\x18\x03 \x01(\bH\x01R\x11includePrivateKey\x88\x01\x01B\x0f\n" +
	"\r_send_currentB\x16\n" +
	"\x14_include_private_key\":\n" +
	"\x15GetTrustBundleRequest\x12!\n" +
	"\ftrust_domain\x18\x01 \x01(\tR\vtrustDomain\"\x17\n" +
	"\x15GetAgentStatusRequest\"\xd3\x06\n" +
	"\x12WorkloadCredential\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\tR\x04slot\x12'\n" +
	"\x0fcertificate_pem\x18\x02 \x01(\tR\x0ecertificatePem\x12&\n" +
	"\x0fprivate_key_pem\x18\x03 \x01(\tR\rprivateKeyPem\x122\n" +
	"\x15certificate_chain_pem\x18\x04 \x01(\tR\x13certificateChainPem\x12(\n" +
	"\x10trust_bundle_pem\x18\x05 \x01(\tR\x0etrustBundlePem\x12!\n" +
	"\ftrust_domain\x18\x06 \x01(\tR\vtrustDomain\x12\x19\n" +
	"\bagent_id\x18\a \x01(\tR\aagentId\x12\x17\n" +
	"\anode_id\x18\b \x01(\tR\x06nodeId\x12\x1f\n" +
	"\videntity_id\x18\t \x01(\tR\n" +
	"identityId\x12\x1d\n" +
	"\n" +
	"session_id\x18\n" +
	" \x01(\tR\tsessionId\x12\x19\n" +
	"\blease_id\x18\v \x01(\tR\aleaseId\x12(\n" +
	"\x10renewal_group_id\x18\f \x01(\tR\x0erenewalGroupId\x12\x1b\n" +
	"\tspiffe_id\x18\r \x01(\tR\bspiffeId\x12\x1b\n" +
	"\tdns_names\x18\x0e \x03(\tR\bdnsNames\x12#\n" +
	"\rserial_number\x18\x0f \x01(\tR\fserialNumber\x12$\n" +
	"\x0ekey_version_id\x18\x10 \x01(\tR\fkeyVersionId\x12*\n" +
	"\x11key_version_label\x18\x11 \x01(\tR\x0fkeyVersionLabel\x12\x1b\n" +
	"\tbundle_id\x18\x12 \x01(\tR\bbundleId\x12%\n" +
	"\x0ebundle_version\x18\x13 \x01(\x03R\rbundleVersion\x12-\n" +
	"\x12certificate_sha256\x18\x14 \x01(\tR\x11certificateSha256\x12\x1d\n" +
	"\n" +
	"not_before\x18\x15 \x01(\tR\tnotBefore\x12\x1b\n" +
	"\tnot_after\x18\x16 \x01(\tR\bnotAfter\x12\x1f\n" +
	"\vrenew_after\x18\x17 \x01(\tR\n" +
	"renewAfter\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x18 \x01(\tR\tupdatedAt\"\xd8\x01\n" +
	"\vTrustBundle\x12!\n" +
	"\ftrust_domain\x18\x01 \x01(\tR\vtrustDomain\x12\x1b\n" +
	"\tbundle_id\x18\x02 \x01(\tR\bbundleId\x12%\n" +
	"\x0ebundle_version\x18\x03 \x01(\x03R\rbundleVersion\x12$\n" +
	"\x0ekey_version_id\x18\x04 \x01(\tR\fkeyVersionId\x12\x1d\n" +
	"\n" +
	"bundle_pem\x18\x05 \x01(\tR\tbundlePem\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"\x81\x03\n" +
	"\vAgentStatus\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12!\n" +
	"\ftrust_domain\x18\x04 \x01(\tR\vtrustDomain\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x12\x17\n" +
	"\anode_id\x18\x06 \x01(\tR\x06nodeId\x12&\n" +
	"\x0flast_renewal_at\x18\a \x01(\tR\rlastRenewalAt\x12\x1d\n" +
	"\n" +
	"last_error\x18\b \x01(\tR\tlastError\x12\x19\n" +
	"\buds_path\x18\t \x01(\tR\audsPath\x12\x1d\n" +
	"\n" +
	"started_at\x18\n" +
	" \x01(\tR\tstartedAt\x12%\n" +
	"\x0ebundle_version\x18\v \x01(\x03R\rbundleVersion\x12$\n" +
	"\x0ekey_version_id\x18\f \x01(\tR\fkeyVersionId2\xcf\x03\n" +
	"\x19WorkloadCredentialService\x12w\n" +
	"\x17FetchWorkloadCredential\x123.stellguard.agent.v1.FetchWorkloadCredentialRequest\x1a'.stellguard.agent.v1.WorkloadCredential\x12y\n" +
	"\x17WatchWorkloadCredential\x123.stellguard.agent.v1.WatchWorkloadCredentialRequest\x1a'.stellguard.agent.v1.WorkloadCredential0\x01\x12^\n" +
	"\x0eGetTrustBundle\x12*.stellguard.agent.v1.GetTrustBundleRequest\x1a .stellguard.agent.v1.TrustBundle\x12^\n" +
	"\x0eGetAgentStatus\x12*.stellguard.agent.v1.GetAgentStatusRequest\x1a .stellguard.agent.v1.AgentStatusBIZGgithub.com/stellhub/stellguard-go-sdk/proto/stellguard/agent/v1;agentv1b\x06proto3"

var (
	file_proto_stellguard_agent_v1_workload_proto_rawDescOnce sync.Once
	file_proto_stellguard_agent_v1_workload_proto_rawDescData []byte
)

func file_proto_stellguard_agent_v1_workload_proto_rawDescGZIP() []byte {
	file_proto_stellguard_agent_v1_workload_proto_rawDescOnce.Do(func() {
		file_proto_stellguard_agent_v1_workload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_stellguard_agent_v1_workload_proto_rawDesc), len(file_proto_stellguard_agent_v1_workload_proto_rawDesc)))
	})
	return file_proto_stellguard_agent_v1_workload_proto_rawDescData
}

var file_proto_stellguard_agent_v1_workload_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_stellguard_agent_v1_workload_proto_goTypes = []any{
	(*FetchWorkloadCredentialRequest)(nil), // 0: stellguard.agent.v1.FetchWorkloadCredentialRequest
	(*WatchWorkloadCredentialRequest)(nil), // 1: stellguard.agent.v1.WatchWorkloadCredentialRequest
	(*GetTrustBundleRequest)(nil),          // 2: stellguard.agent.v1.GetTrustBundleRequest
	(*GetAgentStatusRequest)(nil),          // 3: stellguard.agent.v1.GetAgentStatusRequest
	(*WorkloadCredential)(nil),             // 4: stellguard.agent.v1.WorkloadCredential
	(*TrustBundle)(nil),                    // 5: stellguard.agent.v1.TrustBundle
	(*AgentStatus)(nil),                    // 6: stellguard.agent.v1.AgentStatus
}
var file_proto_stellguard_agent_v1_workload_proto_depIdxs = []int32{
	0, // 0: stellguard.agent.v1.WorkloadCredentialService.FetchWorkloadCredential:input_type -> stellguard.agent.v1.FetchWorkloadCredentialRequest
	1, // 1: stellguard.agent.v1.WorkloadCredentialService.WatchWorkloadCredential:input_type -> stellguard.agent.v1.WatchWorkloadCredentialRequest
	2, // 2: stellguard.agent.v1.WorkloadCredentialService.GetTrustBundle:input_type -> stellguard.agent.v1.GetTrustBundleRequest
	3, // 3: stellguard.agent.v1.WorkloadCredentialService.GetAgentStatus:input_type -> stellguard.agent.v1.GetAgentStatusRequest
	4, // 4: stellguard.agent.v1.WorkloadCredentialService.FetchWorkloadCredential:output_type -> stellguard.agent.v1.WorkloadCredential
	4, // 5: stellguard.agent.v1.WorkloadCredentialService.WatchWorkloadCredential:output_type -> stellguard.agent.v1.WorkloadCredential
	5, // 6: stellguard.agent.v1.WorkloadCredentialService.GetTrustBundle:output_type -> stellguard.agent.v1.TrustBundle
	6, // 7: stellguard.agent.v1.WorkloadCredentialService.GetAgentStatus:output_type -> stellguard.agent.v1.AgentStatus
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_stellguard_agent_v1_workload_proto_init() }
func file_proto_stellguard_agent_v1_workload_proto_init() {
	if File_proto_stellguard_agent_v1_workload_proto != nil {
		return
	}
	file_proto_stellguard_agent_v1_workload_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_stellguard_agent_v1_workload_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_stellguard_agent_v1_workload_proto_rawDesc), len(file_proto_stellguard_agent_v1_workload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_stellguard_agent_v1_workload_proto_goTypes,
		DependencyIndexes: file_proto_stellguard_agent_v1_workload_proto_depIdxs,
		MessageInfos:      file_proto_stellguard_agent_v1_workload_proto_msgTypes,
	}.Build()
	File_proto_stellguard_agent_v1_workload_proto = out.File
	file_proto_stellguard_agent_v1_workload_proto_goTypes = nil
	file_proto_stellguard_agent_v1_workload_proto_depIdxs = nil
}
