// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.2
// source: proto/stellguard/agent/v1/workload.proto

package agentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkloadCredentialService_FetchWorkloadCredential_FullMethodName = "/stellguard.agent.v1.WorkloadCredentialService/FetchWorkloadCredential"
	WorkloadCredentialService_WatchWorkloadCredential_FullMethodName = "/stellguard.agent.v1.WorkloadCredentialService/WatchWorkloadCredential"
	WorkloadCredentialService_GetTrustBundle_FullMethodName          = "/stellguard.agent.v1.WorkloadCredentialService/GetTrustBundle"
	WorkloadCredentialService_GetAgentStatus_FullMethodName          = "/stellguard.agent.v1.WorkloadCredentialService/GetAgentStatus"
)

// WorkloadCredentialServiceClient is the client API for WorkloadCredentialService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkloadCredentialServiceClient interface {
	FetchWorkloadCredential(ctx context.Context, in *FetchWorkloadCredentialRequest, opts ...grpc.CallOption) (*WorkloadCredential, error)
	WatchWorkloadCredential(ctx context.Context, in *WatchWorkloadCredentialRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorkloadCredential], error)
	GetTrustBundle(ctx context.Context, in *GetTrustBundleRequest, opts ...grpc.CallOption) (*TrustBundle, error)
	GetAgentStatus(ctx context.Context, in *GetAgentStatusRequest, opts ...grpc.CallOption) (*AgentStatus, error)
}

type workloadCredentialServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkloadCredentialServiceClient(cc grpc.ClientConnInterface) WorkloadCredentialServiceClient {
	return &workloadCredentialServiceClient{cc}
}

func (c *workloadCredentialServiceClient) FetchWorkloadCredential(ctx context.Context, in *FetchWorkloadCredentialRequest, opts ...grpc.CallOption) (*WorkloadCredential, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkloadCredential)
	err := c.cc.Invoke(ctx, WorkloadCredentialService_FetchWorkloadCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workloadCredentialServiceClient) WatchWorkloadCredential(ctx context.Context, in *WatchWorkloadCredentialRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorkloadCredential], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkloadCredentialService_ServiceDesc.Streams[0], WorkloadCredentialService_WatchWorkloadCredential_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchWorkloadCredentialRequest, WorkloadCredential]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkloadCredentialService_WatchWorkloadCredentialClient = grpc.ServerStreamingClient[WorkloadCredential]

func (c *workloadCredentialServiceClient) GetTrustBundle(ctx context.Context, in *GetTrustBundleRequest, opts ...grpc.CallOption) (*TrustBundle, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrustBundle)
	err := c.cc.Invoke(ctx, WorkloadCredentialService_GetTrustBundle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workloadCredentialServiceClient) GetAgentStatus(ctx context.Context, in *GetAgentStatusRequest, opts ...grpc.CallOption) (*AgentStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentStatus)
	err := c.cc.Invoke(ctx, WorkloadCredentialService_GetAgentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkloadCredentialServiceServer is the server API for WorkloadCredentialService service.
// All implementations must embed UnimplementedWorkloadCredentialServiceServer
// for forward compatibility.
type WorkloadCredentialServiceServer interface {
	FetchWorkloadCredential(context.Context, *FetchWorkloadCredentialRequest) (*WorkloadCredential, error)
	WatchWorkloadCredential(*WatchWorkloadCredentialRequest, grpc.ServerStreamingServer[WorkloadCredential]) error
	GetTrustBundle(context.Context, *GetTrustBundleRequest) (*TrustBundle, error)
	GetAgentStatus(context.Context, *GetAgentStatusRequest) (*AgentStatus, error)
	mustEmbedUnimplementedWorkloadCredentialServiceServer()
}

// UnimplementedWorkloadCredentialServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkloadCredentialServiceServer struct{}

func (UnimplementedWorkloadCredentialServiceServer) FetchWorkloadCredential(context.Context, *FetchWorkloadCredentialRequest) (*WorkloadCredential, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchWorkloadCredential not implemented")
}
func (UnimplementedWorkloadCredentialServiceServer) WatchWorkloadCredential(*WatchWorkloadCredentialRequest, grpc.ServerStreamingServer[WorkloadCredential]) error {
	return status.Error(codes.Unimplemented, "method WatchWorkloadCredential not implemented")
}
func (UnimplementedWorkloadCredentialServiceServer) GetTrustBundle(context.Context, *GetTrustBundleRequest) (*TrustBundle, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrustBundle not implemented")
}
func (UnimplementedWorkloadCredentialServiceServer) GetAgentStatus(context.Context, *GetAgentStatusRequest) (*AgentStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgentStatus not implemented")
}
func (UnimplementedWorkloadCredentialServiceServer) mustEmbedUnimplementedWorkloadCredentialServiceServer() {
}
func (UnimplementedWorkloadCredentialServiceServer) testEmbeddedByValue() {}

// UnsafeWorkloadCredentialServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkloadCredentialServiceServer will
// result in compilation errors.
type UnsafeWorkloadCredentialServiceServer interface {
	mustEmbedUnimplementedWorkloadCredentialServiceServer()
}

func RegisterWorkloadCredentialServiceServer(s grpc.ServiceRegistrar, srv WorkloadCredentialServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkloadCredentialServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkloadCredentialService_ServiceDesc, srv)
}

func _WorkloadCredentialService_FetchWorkloadCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchWorkloadCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkloadCredentialServiceServer).FetchWorkloadCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkloadCredentialService_FetchWorkloadCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkloadCredentialServiceServer).FetchWorkloadCredential(ctx, req.(*FetchWorkloadCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkloadCredentialService_WatchWorkloadCredential_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchWorkloadCredentialRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkloadCredentialServiceServer).WatchWorkloadCredential(m, &grpc.GenericServerStream[WatchWorkloadCredentialRequest, WorkloadCredential]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkloadCredentialService_WatchWorkloadCredentialServer = grpc.ServerStreamingServer[WorkloadCredential]

func _WorkloadCredentialService_GetTrustBundle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrustBundleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkloadCredentialServiceServer).GetTrustBundle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkloadCredentialService_GetTrustBundle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkloadCredentialServiceServer).GetTrustBundle(ctx, req.(*GetTrustBundleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkloadCredentialService_GetAgentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkloadCredentialServiceServer).GetAgentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkloadCredentialService_GetAgentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkloadCredentialServiceServer).GetAgentStatus(ctx, req.(*GetAgentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkloadCredentialService_ServiceDesc is the grpc.ServiceDesc for WorkloadCredentialService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkloadCredentialService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stellguard.agent.v1.WorkloadCredentialService",
	HandlerType: (*WorkloadCredentialServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchWorkloadCredential",
			Handler:    _WorkloadCredentialService_FetchWorkloadCredential_Handler,
		},
		{
			MethodName: "GetTrustBundle",
			Handler:    _WorkloadCredentialService_GetTrustBundle_Handler,
		},
		{
			MethodName: "GetAgentStatus",
			Handler:    _WorkloadCredentialService_GetAgentStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchWorkloadCredential",
			Handler:       _WorkloadCredentialService_WatchWorkloadCredential_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/stellguard/agent/v1/workload.proto",
}
